---

- name: Install jenkins
  hosts: jenkins
  gather_facts: no
  become: yes
  pre_tasks:
  - name: setup python @Debian like
    raw:  apt-get update && apt-get -y install python lsb-release
    ignore_errors: True
  - name: Gathering facts
    setup:
  roles:
#  - jenkins_with_nginx
#  - jenkins
  - jenkins_node
