---
- name: create nginx repo
  copy:
   dest: /etc/yum.repos.d/nginx.repo
   content: |
       [nginx]
       name=nginx repo
       baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
       gpgcheck=0
       enabled=1

- name: Install nginx for CentOS7
  yum:
    name: nginx
    state: latest

- name: copy config for jenkins vhost
  template:
    src: centos7_jenkins.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644

- name: Start nginx
  systemd:
    name: nginx
    state: restarted

- name: enable nginx
  systemd:
    name: nginx
    enabled: true
