---
- block:
    - name: Install first part of soft
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker
      yum:
        name: install docker components
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start docker
      systemd:
        name: docker
        state: restarted

    - name: enable docker
      systemd:
        name: docker
        enabled: true

    - name: add centos user to docker group
      shell: usermod -aG docker centos
      register: result
      changed_when: false

    - name: Run a command as the apache user
      command: ssh-keygen -f ~/.ssh/id_rsa -P ""
      become_user: centos

    - name: install docker-compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
        chmod 755 /usr/bin/docker-compose

  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
