---
- block: #--- block for RedHat ---#
    - name: upgrade all packages
      yum: name=* state=latest

    - name: Install additional soft
      yum:
        name:
          - java-1.8.0-openjdk-devel
          - epel-release
          - curl
          - vim
          - nc
          - wget
          - openssl
          - git
        state: present

    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Modify hosts
      lineinfile:
        dest: /etc/hosts
        line: '{{ ansible_default_ipv4.address }} {{ hostname }}'

# awscli installation
    - name: Install python3
      yum:
        name:
          - python36
        state: present

    - name: install pip3 and awscli
      shell: |
        curl -O https://bootstrap.pypa.io/get-pip.py
        python3 get-pip.py
        /usr/local/bin/pip3 install awscli
        if [ -d /var/lib/jenkins/ ]; then echo 'export PATH=/usr/local/bin:$PATH' >> /var/lib/jenkins/.bashrc;fi
        if [ -d /root/ ]; then echo 'export PATH=/usr/local/bin:$PATH' >> /root/.bashrc;fi
      args:
        chdir: /tmp

  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
